### ISSUE TITLE
Quit updating releases over previous release so it has the correct date

### ISSUE THREAD

**Issue by Rizadium** [QIDITECH/QIDI_PLUS4#17]
![image](https://github.com/user-attachments/assets/981b69a7-98ee-4bde-b6b8-a4d5e86a1160)
Hard to keep track when a release 3 days ago says it was released on September 20th which is not even remotely true.

**Comment by QIDITECH** [comment]
Due to the serious bugs in 1.4.2, in order to avoid incorrect installation by customers, we directly replaced the old version instead of creating a new version when the new version was released.
You can determine the exact time based on the file upload date.
![image](https://github.com/user-attachments/assets/ab5d2edb-cbd5-470a-8219-d651ec157d2f)
