### ISSUE TITLE
After printing starts, Klipper stops when connecting through a browser via Fluidd

### ISSUE THREAD

**Issue by Ken6432** [QIDITECH/QIDI_PLUS4#33]
After updating the firmware to 1.6.0, I have had the printer abort printing when I have browsed to the IP address through my iPad browser.  This has happened consistently each time I do it.  It only happens after the print job is underway.  I was able to connect without issue after the nozzle cleaning step, while the bed was coming up to temperature, but when I tried again after the printing started, the job immediately aborted.

Also, after this happens, the RESUME_INTERRUPTED macro does not restart the job correctly.  It seems to have the print head start printing in mid air as if it does not know the correct offset to use.  I have not used the RESUME_INTERRUPTED macro prior to updating the firmware, so I don't know if this is a 1.6.0 related issue or not.

**Comment by Ken6432** [comment]
I cannot seem to reproduce this again (even though it was happening regularly before), so I am closing it.

**Comment by Ken6432** [comment]
I cannot seem to reproduce this again (even though it was happening regularly before), so I am closing it.

**Comment by QIDITECH** [comment]
This may be related to #32, which is solved when you unplug the wifi adapter.

**Comment by kamermans** [comment]
I have observed this as well, twice in the last 24 hours.  During a very complex print, checking the status causes Klipper to crash, in my case with `MCU 'U_1' shutdown: Timer too close`.  Since Fluidd is only client-side, making API calls to Moonraker, I'm tempted to reduce the CPU priority of Moonraker itself.  This only seems to happen for me with prints that have hundreds of objects on the same plate.  By default 1.6.0 crashes before the print even starts, but after adjusting many process priorities, it does run, I just can't check the progress 😂 

In my case this problem seems to become more prevalent with more objects on the plate, so I assume the issue is with per-object data coming from Moonraker, like the per-object exclusion list or something.
